name: fib service unit tests
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fib
    steps:
      - name: setup python
        uses: |
          actions/checkout@v2
          actions/setup-python@v2

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up test database
        run: |
          python manage.py migrate
          python manage.py makemigrations
          python manage.py migrate