name: fib service unit tests
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: pytest --ds=fib.test_settings